platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'ProjectBarcodeScanner' do
  # Pods for ProjectBarcodeScanner
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'BarcodeDetectorMLKit'
]

  target 'ProjectBarcodeScannerTests' do
    inherit! :search_paths
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
end

target 'ProjectBarcodeScanner-tvOS' do
  # Pods for ProjectBarcodeScanner-tvOS

  target 'ProjectBarcodeScanner-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
